let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
	  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'itchyny/lightline.vim'
Plug 'catppuccin/vim', {'as': 'catppuccin'}
call plug#end()

set laststatus=2
if !has('gui_running')
  set t_Co=256
endif
set termguicolors
set noshowmode
let g:lightline = {'colorscheme': 'catppuccin_mocha'}
colorscheme catppuccin_mocha

" g.mapleader = ' '
" g.maplocalleader = ' '

" number lines and relative number lines
set number
set relativenumber
set cursorline
" set showmatch

 " indenting
set breakindent
set smartindent
set autoindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smarttab

 " search highlight
set ignorecase
set smartcase
set nohlsearch
set incsearch

set scrolloff=8
