
-- return {
--     s({ trig = ";a", snippetType = "autosnippet" },
--         {
--             t("\\alpha"),
--         }),
--
--     -- -- snippet to make simple snippets
--     -- s({ trig = "mkls", snippetType = "autosnippet" },
--     --     fmta(
--     --         [[
--     --        s({trig="<>", snippetType="autosnippet"},
--     --            {
--     --                t("<>"),
--     --            }
--     --        ),
--     --        ]]
--     --     )
--     -- ),
--
-- }
